main = "index.js"
compatibility_date = "2025-06-30"

[observability]
enabled = true

[assets]
directory          = "./dist"
binding            = "ASSETS"
not_found_handling = "single-page-application"

[env.dev]
name   = "invest-v3-dev"
routes = [
  { pattern = "derwa-demo.k-f.dev", custom_domain = true }
]

[env.prod]
name   = "invest-v3-prod"        
routes = [
  { pattern = "beta.app.centrifuge.io", custom_domain = true }
]
