name: 'Lighthouse Test GH action'
description: 'Run Lighthouse performance tests'

inputs:
  deployment-url:
    description: 'URL of the deployed application to test'
    required: true
  github-token:
    description: 'GitHub token for Lighthouse CI'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '📊 Performance Test with Lighthouse'
      id: lighthouse
      shell: bash
      run: |
        # Install Lighthouse CI
        npm install -g @lhci/cli
        
        # Run Lighthouse CI on the deployed URL and capture report URL
        set -o pipefail
        lhci autorun --config=lighthouserc.json --collect.url=${{ inputs.deployment-url }} 2>&1 | tee lhci-test.out
        REPORT_URL=$(grep -Eo 'https://storage.googleapis.com/[^ ]+\.html' lhci-test.out | tail -n1)
        if [ -n "$REPORT_URL" ]; then
          echo "report_url=$REPORT_URL" >> $GITHUB_OUTPUT
          echo "Lighthouse report URL: $REPORT_URL"
          echo "DEBUG: Set output report_url to: $REPORT_URL"
        else
          echo "report_url=" >> $GITHUB_OUTPUT
          echo "No Lighthouse report URL found"
          echo "DEBUG: Set output report_url to empty"
        fi
        
        # Debug: Check what was actually set
        echo "DEBUG: Checking GITHUB_OUTPUT file contents:"
        cat $GITHUB_OUTPUT
      env:
        LHCI_GITHUB_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true
    
    - name: '🔍 Debug Lighthouse Output'
      shell: sh
      if: github.event_name == 'pull_request'
      run: |
        echo "Lighthouse output report_url: '${{ steps.lighthouse.outputs.report_url }}'"
        echo "Lighthouse output length: ${#LIGHTHOUSE_URL}"
        echo "Lighthouse step outcome: ${{ steps.lighthouse.outcome }}"
      env:
        LIGHTHOUSE_URL: ${{ steps.lighthouse.outputs.report_url }}
outputs:
  report-url:
    description: 'URL of the Lighthouse report'
    value: ${{ steps.lighthouse.outputs.report_url }}
