name: 'Lighthouse Test GH action'
description: 'Run Lighthouse performance tests'

inputs:
  deployment-url:
    description: 'URL of the deployed application to test'
    required: true
  github-token:
    description: 'GitHub token for Lighthouse CI'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '📊 Performance Test with Lighthouse'
      id: lighthouse
      shell: bash
      run: |
        # Install Lighthouse CI
        npm install -g @lhci/cli
        
        # Run Lighthouse CI on the deployed URL and capture report URL
        set -o pipefail
        lhci autorun --config=lighthouserc.json --collect.url=${{ inputs.deployment-url }} --collect.numberOfRuns=2 2>&1 | tee lhci.out
        REPORT_URL=$(grep -Eo 'https://storage.googleapis.com/[^ ]+\.html' lhci.out | tail -n1)
        if [ -n "$REPORT_URL" ]; then
          echo "report_url=$REPORT_URL" >> $GITHUB_OUTPUT
          echo "Lighthouse report URL: $REPORT_URL"
        fi
      env:
        LHCI_GITHUB_TOKEN: ${{ inputs.github-token }}
      continue-on-error: true

outputs:
  report-url:
    description: 'URL of the Lighthouse report'
    value: ${{ steps.lighthouse.outputs.report_url }}
