name: Auto-label new PRs

# Use pull_request_target for fork safety (no checkout of PR code)
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add default label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs-review
