name: '🔄 Manual Rollback'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to roll back'
        required: true
        type: choice
        options:
          - staging
          - prod
      tag:
        description: 'Release tag to roll back to (e.g., v1.1.6)'
        required: true
        type: string

jobs:
  rollback:
    name: 'Rollback to ${{ github.event.inputs.tag }} on ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: launchpad-bundle${{ github.event.inputs.tag }}.zip
      APP_DIR: launchpad

    steps:
      - name: '📥 Checkout Code from Release Tag'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: '📦 Download Release Artifact'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p $APP_DIR
          echo "⬇️  Downloading $ARTIFACT_NAME from release ${{ github.event.inputs.tag }}"
          gh release download ${{ github.event.inputs.tag }} \
            --repo ${{ github.repository }} \
            --pattern "$ARTIFACT_NAME" \
            --dir "$APP_DIR"

          cd "$APP_DIR"
          unzip -q "$ARTIFACT_NAME" -d dist
          echo "✅ Artifact extracted to $APP_DIR/dist"

      - name: '🚀 Deploy Rollback to Cloudflare'
        uses: ./.github/actions/deploy-app
        with:
          environment: ${{ github.event.inputs.environment == 'prod' && 'prod' || 'staging' }}
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
