name: '🔄 Manual Rollback'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to roll back to (e.g., v1.1.6)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  rollback:
    name: 'Rollback to ${{ github.event.inputs.tag }}'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - name: '📥 Checkout Code from Release Tag'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: '📦 Setup pnpm (for Wrangler)'
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: '📦 Install Wrangler'
        shell: sh
        run: |
          npm install -g wrangler@4.33.1          
      - name: version id setup
        id: wrangler-command
        run: |
          WORKER_NAME=$(grep -A1 "\[env.prod\]" wrangler.toml | grep "name" | cut -d'"' -f2)
          WRANGLER_ENV="prod"
          VERSION_ID=$(wrangler versions list --name $WORKER_NAME --env $WRANGLER_ENV --json | jq -r ".[] | select(.annotations.\"workers/tag\" == \"${{ inputs.tag }}\") | .id" | head -1)
          CMD="versions deploy $VERSION_ID@100% --env $WRANGLER_ENV --yes"
          echo "cmd=$CMD" >> $GITHUB_OUTPUT

      - name: '🚀 Deploy to Cloudflare'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: ${{ steps.wrangler-command.outputs.cmd }}
          wranglerVersion: "4.45.0"
        id: deploy
