name: '🔄 Manual Rollback'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to roll back'
        required: true
        type: choice
        options:
          - staging
          - prod
      tag:
        description: 'The stable release tag to roll back to (e.g., v1.2.0)'
        required: true
        type: string

jobs:
  rollback-and-deploy:
    name: 'Roll Back to ${{ github.event.inputs.tag }} on ${{ github.event.inputs.environment }}'
    environment: ${{ github.event.inputs.environment == 'prod' && 'prod' || null }}
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: launchpad-bundle*.zip
      app-name: 'launchpad'
    steps:
      - name: '📥 Checkout code from release tag'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: '📦 Download Build Artifact from Release'
        run: |
          gh release download ${{ github.event.inputs.tag }} \
            --repo centrifuge/apps-invest-v3 \
            --pattern "$ARTIFACT_NAME" \
            --dir ./${{ env.app-name }}
          cd ./${{ env.app-name }}
          unzip "$ARTIFACT_NAME" -d dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: '🚀 Deploy to Cloudflare'
        run: |
          cd ${{ env.app-name }}
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} wrangler deploy --env prod
          else
            CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} wrangler versions upload --env prod --preview-alias staging
          fi
